# Generated by Django 4.2.9 on 2024-02-04 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("social_media", "0003_profile_followers_alter_profile_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="followers",
        ),
        migrations.AlterField(
            model_name="follow",
            name="followed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to="social_media.profile",
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to="social_media.profile",
            ),
        ),
    ]
